[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault = "6uyR4Zo5spqveu1yxXQUQ5HSM1a25WfVi89HW96MLKsR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -- --nocapture"
